var bt= document.querySelectorAll(".lid-toggle")
console.log(bt[1])
var stat = document.querySelector(".feature")
console.log(stat)
var htmlcol=document.getElementsByClassName("feature backpack__lid")
console.log(htmlcol)
console.log("element is: ", htmlcol[0].getElementsByTagName("span"))
var id = document.getElementById("pack02")
console.log(id)
var child = id.getElementsByTagName("span")
console.log("child is ", child)
